name: Schedule API Call

on:
  schedule:
    - cron: '* * * * *' # Executa a cada minuto

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Call the API
        run: curl -X GET https://tb-barber.vercel.app/api/updateBooking
